-- Database: Project4

-- DROP DATABASE IF EXISTS "Project4";

CREATE DATABASE "Project4"
    WITH
    OWNER = imira
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

    -- Switch to the database
    \c Project4


    -- Table creation for roles

    -- DROP TABLE IF EXISTS public.role;

    CREATE TABLE IF NOT EXISTS public.role
    (
        role_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        description character varying(1000) COLLATE pg_catalog."default",
        name character varying(255) COLLATE pg_catalog."default" NOT NULL,
        CONSTRAINT role_pkey PRIMARY KEY (role_id)
    )

INSERT INTO role (role_id, description, name) VALUES
(1, 'Administrator with full privileges', 'Admin'),
(2, 'Standard user with limited privileges', 'Volunteer'),
(3, 'Organization account with privileges to manage opportunities', 'Organization');

INSERT INTO user_profile (
    profile_id, first_name, last_name, profile_pic
) VALUES
(1, 'Fatema', 'Marhoon', NULL),
(2, 'Jane', 'Smith', NULL),
(3, 'Jane', 'Smith', NULL);


INSERT INTO users (
    uid, email, is_enabled, first_name, is_organization, is_volunteer, last_name, password, reset_token, status, token_expiration_time, verification_code, profile_id, role_id
) VALUES
(1, 'ifatima.marhoon@gmail.com', TRUE, 'Fatema', FALSE, FALSE, 'Marhoon', '$2a$10$mRPGakgA6LLChWtkBhaiSuvgByBRrcPEWaB5ZcOVBzNGpTfcOCaBy', NULL, TRUE, NULL, NULL, 1, 1),
(2, 'ifatima.marhoon+1@gmail.com', TRUE, 'Jane', TRUE, FALSE, 'Smith', '$2a$10$2Y4yxJjTlJRmYdnvzghcnuKHd27YYZErjDjYiBfKrXbL6onzCjYAO', NULL, TRUE, NULL, NULL, 2, 3),
(3, 'ifatima.marhoon+2@gmail.com', TRUE, 'Jane', FALSE, TRUE, 'Smith', '$2a$10$NENfMskKeZdWYrj55n.ByuRIJRuSaE9Z4SwDW3GxREgiGN2zHxYd2', NULL, TRUE, NULL, NULL, 3, 2);

INSERT INTO organization (
    organization_id, contact_info, description, name, status, user_id
) VALUES
(1, '123-456-7890', 'A nonprofit organization focusing on community support', 'Helping Hands', 'APPROVED', 2);
