-- Database: Project4

-- DROP DATABASE IF EXISTS "Project4";

CREATE DATABASE "Project4"
    WITH
    OWNER = imira
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

    -- Switch to the database
    \c Project4


    -- Table creation for roles

    -- DROP TABLE IF EXISTS public.role;

    CREATE TABLE IF NOT EXISTS public.role
    (
        role_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        description character varying(1000) COLLATE pg_catalog."default",
        name character varying(255) COLLATE pg_catalog."default" NOT NULL,
        CONSTRAINT role_pkey PRIMARY KEY (role_id)
    )

INSERT INTO role (role_id, description, name) VALUES
(1, 'Administrator with full privileges', 'Admin'),
(2, 'Standard user with limited privileges', 'Volunteer'),
(3, 'Organization account with privileges to manage opportunities', 'Organization');
