name: CI

on:
  push:
    branches:
      - main  # or your main branch name
  pull_request:
    branches:
      - main  # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres:11.4
        env:
          POSTGRES_DB: java_to_dev_app_db
          POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the JAR
        run: mvn package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Remove existing Docker containers
        run: |
          docker ps -aq | xargs docker rm -f || true

      - name: Start PostgreSQL service with retries
        run: |
          for i in {1..5}; do
            docker-compose up -d postgres_db && break || sleep 5
          done

      - name: Build and Run Tests
        run: |
          docker-compose build
          docker-compose up -d api_service  # Start your application service
          docker-compose up test_service  # Run tests

      - name: Clean up
        run: docker-compose down
